
* blender-vla
** DONE support coordsys left
   :LOGBOOK:
   - State -> "TODO"  [2015-03-06 Fri]
   - State -> "DONE"  [2015-03-07 Sat]
   :END:

A coordsys left model needs attitude change 180 90 0, and the y axis
inverted.

It is not entirely clear what the correct transformation is, but I have
settled on one through experiment that at least works when exporting to
3ds or obj formats, though exported fbx models are rotated 180 degrees
around the Z axis compared to what I expect.

Export plugins generally have options for which axis is considered "up"
and "forward", but as far as I can tell, Digistar does not respect these
settings.

** DONE option to scale the models down while reading
   :LOGBOOK:
   - State -> "TODO"  [2015-03-05 Thu]
   - State -> "DONE"  [2015-03-05 Thu]
   :END:

One commonly finds models which are in meters (coordsys left) but the
coordinates are all very large because they were converted from files
specified in lightyears.  We should at the very least have an option to
divide out lightyears.  Then maybe an additional scale option after that?

* vlaview
** TODO auto-compute viewport
   :LOGBOOK:
   - State -> "TODO"  [2015-03-05 Thu]
   :END:
* make-asterism
** DONE output asterism-drawing script
   :LOGBOOK:
   - State -> "TODO"  [2015-08-25 Tue]
   - State -> "DONE"  [2015-08-27 Thu]
   :END:

Produce a script that draws a given asterism with one or more trails, and
when it finishes, switch to the vla stick figure.

*** process

 - declare trailclass for each trail

       t1 is trailclass
       t1 position celestial ...
       t1 screenspace off ## what is this?
       t1 frame 1
       t1 intensity 100
       t1 color white
       t1 age on
       t1 lifespan 10
       scene add t1

 - then just move the object
